# Pandas Practice

Notes:
- `DataFrame` = table
- `Series` = one column
- `index` = row labels
- `loc` = access by label
- `iloc` = access by position
- boolean masks filter rows

In [142]:
import pandas as pd
import numpy as np

## 1. DataFrame

- table-like structure
- columns can have different types
- useful for data cleaning and analysis

## 2. Create from list of lists

- good for small structured data
- pass rows and column names

In [143]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [144]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## 3. Create from list of dictionaries

- keys become column names
- easier to read than rows of lists

In [145]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [146]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## 4. Series

- one-dimensional labeled data
- selected from a DataFrame column
- behaves like a column vector

In [147]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [148]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [149]:
df[['Make', 'Model', 'Year']]

      Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

In [150]:
df['id'] = ['nis1', 'hyu1', 'lot2', 'gmc1', 'nis2']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,nis2

In [151]:
df['id'] = [1, 2, 3, 4, 5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [152]:
del df['id']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## 5. Index

- row labels of a DataFrame
- `loc` uses labels
- `iloc` uses positions

In [153]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [154]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [155]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='str')

In [156]:
df.iloc[0]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: 0, dtype: object

In [157]:
df.iloc[[2, 3, 0]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [158]:
idx = np.arange(5)
idx

array([0, 1, 2, 3, 4])

In [159]:
np.random.seed(42)
np.random.shuffle(idx)
idx

array([1, 4, 2, 0, 3])

In [160]:
df = df.iloc[idx]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [161]:
df.iloc[[0, 1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [162]:
df.index

Index([1, 4, 2, 0, 3], dtype='int64')

In [163]:
df.loc[[0, 1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [164]:
df.iloc[[0, 1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [165]:
df.iloc[0,1]

'Sonata'

In [166]:
df.loc[0, 'Model']

'Stanza'

In [167]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
1,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [168]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [169]:
df = df.reset_index(drop=True)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
1,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

## 6. Element-wise operations

- boolean conditions create filters
- operations apply to each value in a Series

In [170]:
df['Engine Cylinders']

0    4
1    6
2    4
3    4
4    4
Name: Engine Cylinders, dtype: int64

In [171]:
df['Engine Cylinders'] * 2

0     8
1    12
2     8
3     8
4     8
Name: Engine Cylinders, dtype: int64

In [172]:
df['Year']

0    2017
1    2017
2    2010
3    1991
4    2017
Name: Year, dtype: int64

In [173]:
above_2010 = df['Year'] > 2010
above_2010

0     True
1     True
2    False
3    False
4     True
Name: Year, dtype: bool

In [174]:
nissan = df['Make'] == 'Nissan'
nissan

0    False
1     True
2    False
3     True
4    False
Name: Make, dtype: bool

In [175]:
df[above_2010 & nissan]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## 7. Filtering

- combine conditions with `&`
- use boolean masks to keep rows

In [176]:
df[nissan]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
3,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [177]:
automatic = df['Transmission Type'] == 'AUTOMATIC'
df[above_2010 & automatic]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

## 8. String operations

- useful for cleaning text columns
- `.str.lower()` and `.str.replace()`

In [178]:
df['Vehicle_Style']

0          Sedan
1         Pickup
2    convertible
3          sedan
4        4dr SUV
Name: Vehicle_Style, dtype: str

In [179]:
df['Vehicle_Style'].str.lower()

0          sedan
1         pickup
2    convertible
3          sedan
4        4dr suv
Name: Vehicle_Style, dtype: str

In [180]:
df['Vehicle_Style'].str.replace(' ', '_')

0          Sedan
1         Pickup
2    convertible
3          sedan
4        4dr_SUV
Name: Vehicle_Style, dtype: str

In [181]:
df['Vehicle_Style'].str.lower().str.replace(' ', '_')

0          sedan
1         pickup
2    convertible
3          sedan
4        4dr_suv
Name: Vehicle_Style, dtype: str

In [182]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='str')

In [183]:
df.columns.str.lower().str.replace(' ', '_')

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp'],
      dtype='str')

In [184]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
1,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [185]:
df.colums = df.columns = df.columns.str.lower().str.replace(' ', '_')
df

C:\Users\abdel\AppData\Local\Temp\ipykernel_21472\306730821.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.colums = df.columns = df.columns.str.lower().str.replace(' ', '_')

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
1,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [186]:
df.dtypes

make                     str
model                    str
year                   int64
engine_hp            float64
engine_cylinders       int64
transmission_type        str
vehicle_style            str
msrp                   int64
dtype: object

In [187]:
df.dtypes.index

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'msrp'],
      dtype='str')

In [191]:
df.dtypes == 'str'

make                  True
model                 True
year                 False
engine_hp            False
engine_cylinders     False
transmission_type     True
vehicle_style         True
msrp                 False
dtype: bool

In [190]:
df.dtypes[df.dtypes == 'str']

make                 str
model                str
transmission_type    str
vehicle_style        str
dtype: object

In [193]:
df.dtypes[df.dtypes == 'str'].index

Index(['make', 'model', 'transmission_type', 'vehicle_style'], dtype='str')

In [194]:
list(df.dtypes[df.dtypes == 'str'].index)

['make', 'model', 'transmission_type', 'vehicle_style']

In [197]:
string_columns = df.dtypes[df.dtypes == 'str'].index

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [198]:
df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,hyundai,sonata,2017,NaN,4,automatic,sedan,27150
1,nissan,frontier,2017,261.0,6,manual,pickup,32340
2,lotus,elise,2010,218.0,4,manual,convertible,54990
3,nissan,stanza,1991,138.0,4,manual,sedan,2000
4,gmc,acadia,2017,194.0,4,automatic,4dr_suv,34450

## 9. Summary operations

- `value_counts()` shows frequency
- `mean`, `sum`, `min`, `max`, `describe`

In [199]:
df.msrp

0    27150
1    32340
2    54990
3     2000
4    34450
Name: msrp, dtype: int64

In [200]:
df.msrp.mean()

np.float64(30186.0)

In [201]:
df.msrp.sum()

np.int64(150930)

In [202]:
df.msrp.min(), df.msrp.max(), df.msrp.mean(), df.msrp.std()

(np.int64(2000),
 np.int64(54990),
 np.float64(30186.0),
 np.float64(18985.044903818372))

In [203]:
df.msrp.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: msrp, dtype: float64

In [205]:
df.mean(numeric_only=True)

year                 2010.40
engine_hp             202.75
engine_cylinders        4.40
msrp                30186.00
dtype: float64

In [206]:
df.describe().round(2)

          year  engine_hp  engine_cylinders      msrp
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [207]:
df.make.nunique()

4

In [208]:
df.nunique()

make                 4
model                5
year                 3
engine_hp            4
engine_cylinders     2
transmission_type    2
vehicle_style        4
msrp                 5
dtype: int64

In [209]:
df.make.value_counts()

make
nissan     2
hyundai    1
lotus      1
gmc        1
Name: count, dtype: int64

In [210]:
df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,hyundai,sonata,2017,NaN,4,automatic,sedan,27150
1,nissan,frontier,2017,261.0,6,manual,pickup,32340
2,lotus,elise,2010,218.0,4,manual,convertible,54990
3,nissan,stanza,1991,138.0,4,manual,sedan,2000
4,gmc,acadia,2017,194.0,4,automatic,4dr_suv,34450

In [211]:
df.isnull()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [212]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            1
engine_cylinders     0
transmission_type    0
vehicle_style        0
msrp                 0
dtype: int64

In [215]:
df.engine_hp.isnull()

0     True
1    False
2    False
3    False
4    False
Name: engine_hp, dtype: bool

In [216]:
df.engine_hp.fillna(0)

0      0.0
1    261.0
2    218.0
3    138.0
4    194.0
Name: engine_hp, dtype: float64

In [217]:
df.engine_hp.fillna(df.engine_hp.mean())

0    202.75
1    261.00
2    218.00
3    138.00
4    194.00
Name: engine_hp, dtype: float64

In [218]:
df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,hyundai,sonata,2017,NaN,4,automatic,sedan,27150
1,nissan,frontier,2017,261.0,6,manual,pickup,32340
2,lotus,elise,2010,218.0,4,manual,convertible,54990
3,nissan,stanza,1991,138.0,4,manual,sedan,2000
4,gmc,acadia,2017,194.0,4,automatic,4dr_suv,34450

In [219]:
df.engine_hp = df.engine_hp.fillna(df.engine_hp.mean())
df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
1,nissan,frontier,2017,261.00,6,manual,pickup,32340
2,lotus,elise,2010,218.00,4,manual,convertible,54990
3,nissan,stanza,1991,138.00,4,manual,sedan,2000
4,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450

## 10. Sorting and Re-Ordering

In [220]:
df

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
0,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
1,nissan,frontier,2017,261.00,6,manual,pickup,32340
2,lotus,elise,2010,218.00,4,manual,convertible,54990
3,nissan,stanza,1991,138.00,4,manual,sedan,2000
4,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450

In [223]:
df.sort_values(by='msrp')

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
3,nissan,stanza,1991,138.00,4,manual,sedan,2000
0,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
1,nissan,frontier,2017,261.00,6,manual,pickup,32340
4,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450
2,lotus,elise,2010,218.00,4,manual,convertible,54990

In [224]:
df.sort_values(by='msrp', ascending=False)

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,msrp
2,lotus,elise,2010,218.00,4,manual,convertible,54990
4,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450
1,nissan,frontier,2017,261.00,6,manual,pickup,32340
0,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
3,nissan,stanza,1991,138.00,4,manual,sedan,2000

## 11. Grouping

In [228]:
df.groupby('transmission_type').msrp.mean()

transmission_type
automatic    30800.000000
manual       29776.666667
Name: msrp, dtype: float64

In [230]:
df_group = df.groupby('transmission_type').msrp.agg(['mean', 'count'])
df_group

                           mean  count
transmission_type
automatic          30800.000000      2
manual             29776.666667      3

In [231]:
df_group['mean'] - df.msrp.mean()

transmission_type
automatic    614.000000
manual      -409.333333
Name: mean, dtype: float64

## 12. Getting the NumPy Array

In [233]:
df.msrp

0    27150
1    32340
2    54990
3     2000
4    34450
Name: msrp, dtype: int64

In [234]:
np.log1p(df.msrp)

0    10.209169
1    10.384091
2    10.914925
3     7.601402
4    10.447293
Name: msrp, dtype: float64

In [239]:
df.msrp.values

array([27150, 32340, 54990,  2000, 34450])

In [240]:
np.log1p(df.msrp.values)

array([10.20916916, 10.38409105, 10.91492481,  7.60140233, 10.4472933 ])

## 13. Convert to dicts

In [243]:
df.to_dict(orient='records')

[{'make': 'hyundai',
  'model': 'sonata',
  'year': 2017,
  'engine_hp': 202.75,
  'engine_cylinders': 4,
  'transmission_type': 'automatic',
  'vehicle_style': 'sedan',
  'msrp': 27150},
 {'make': 'nissan',
  'model': 'frontier',
  'year': 2017,
  'engine_hp': 261.0,
  'engine_cylinders': 6,
  'transmission_type': 'manual',
  'vehicle_style': 'pickup',
  'msrp': 32340},
 {'make': 'lotus',
  'model': 'elise',
  'year': 2010,
  'engine_hp': 218.0,
  'engine_cylinders': 4,
  'transmission_type': 'manual',
  'vehicle_style': 'convertible',
  'msrp': 54990},
 {'make': 'nissan',
  'model': 'stanza',
  'year': 1991,
  'engine_hp': 138.0,
  'engine_cylinders': 4,
  'transmission_type': 'manual',
  'vehicle_style': 'sedan',
  'msrp': 2000},
 {'make': 'gmc',
  'model': 'acadia',
  'year': 2017,
  'engine_hp': 194.0,
  'engine_cylinders': 4,
  'transmission_type': 'automatic',
  'vehicle_style': '4dr_suv',
  'msrp': 34450}]